# Generated by Django 2.1.7 on 2019-03-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('title_field', models.CharField(max_length=30)),
                ('date_field', models.DateField(auto_now=True)),
                ('task_field', models.CharField(max_length=256)),
                ('reward_field', models.CharField(max_length=100)),
            ],
        ),
    ]
