# Generated by Django 2.2 on 2019-04-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_steps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steps',
            old_name='date_field',
            new_name='date_start',
        ),
    ]
