# Generated by Django 2.2 on 2019-04-14 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190408_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='quest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.Quest'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='completion_percent',
            field=models.FloatField(default='0.0'),
        ),
    ]
