# Generated by Django 2.2 on 2019-04-14 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190414_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Quest'),
        ),
    ]
