# Generated by Django 2.2 on 2019-04-14 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190414_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steps',
            name='quest',
        ),
    ]
