# Generated by Django 2.2 on 2019-04-14 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_steps_quest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steps',
            name='quest',
        ),
    ]
