# Generated by Django 2.2 on 2019-04-14 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_steps_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='quest',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myapp.Quest'),
            preserve_default=False,
        ),
    ]
