# Generated by Django 2.2 on 2019-04-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_steps_quest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='step_five',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='steps',
            name='step_four',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='steps',
            name='step_one',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='steps',
            name='step_three',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='steps',
            name='step_two',
            field=models.CharField(default='', max_length=255),
        ),
    ]
