# Generated by Django 2.2 on 2019-04-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20190416_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='step_five_complete',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steps',
            name='step_four_complete',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steps',
            name='step_one_complete',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steps',
            name='step_three_complete',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steps',
            name='step_two_complete',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
