# Generated by Django 2.2 on 2019-04-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20190416_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='step_five',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='steps',
            name='step_five_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='steps',
            name='step_four',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='steps',
            name='step_four_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='steps',
            name='step_one_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='steps',
            name='step_three',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='steps',
            name='step_three_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='steps',
            name='step_two',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='steps',
            name='step_two_complete',
            field=models.BooleanField(default=False),
        ),
    ]
