# Generated by Django 2.2 on 2019-04-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20190420_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='step_five_complete',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='step_four_complete',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='step_one_complete',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='step_three_complete',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='step_two_complete',
            field=models.IntegerField(default='0'),
        ),
    ]
